import type { SessionRuntime } from './state';
import { workspaceKey, privateKey } from '../labs/bundle';

async function runOrThrow(rt: SessionRuntime, argv: readonly [string, ...string[]], what: string): Promise<void> {
  const proc = await rt.backend().exec(argv, { timeout: 60_000 });
  const out = await proc.output();
  if (out.exitCode !== 0) {
    throw new Error(`${what} failed (exit ${out.exitCode}): ${new TextDecoder().decode(out.stderr).slice(0, 500)}`);
  }
}

/**
 * Extracts workspace.tgz (learner-visible files) to /workspace as the
 * `learner` user. Skipped on resume when a snapshot is restored instead
 * (see lifecycle.resume) — restoreBackup() replaces this entirely.
 *
 * Delivery is `writeFile` of the whole archive in one call. If the spike
 * (risk R3) finds that too slow for multi-MB bundles, swap this for a
 * `curl http://bundles.opalix.internal/<key>` exec call instead — the
 * outbound handler in families/egress.ts (`bundlesOutbound`) already serves
 * R2 objects at that host, so only this function would need to change.
 */
export async function hydrateWorkspaceFiles(rt: SessionRuntime, labSlug: string, labVersion: string): Promise<void> {
  const backend = rt.backend();
  const workspaceObj = await rt.env.LABS_BUCKET.get(workspaceKey(labSlug, labVersion));
  if (!workspaceObj) throw new Error(`workspace bundle missing for ${labSlug}@${labVersion}`);
  await backend.writeFile('/tmp/opalix-workspace.tgz', workspaceObj.body);
  await runOrThrow(
    rt,
    ['sh', '-c', 'tar xzf /tmp/opalix-workspace.tgz -C /workspace --no-same-owner && chown -R learner:learner /workspace && rm -f /tmp/opalix-workspace.tgz'],
    'workspace hydrate'
  );
}

/**
 * Extracts only pressure/ from private.tgz to /opt/lab, persistently for
 * the session's lifetime (root-owned, 0700 — pressure events fire on a
 * schedule throughout the session so their scripts must already be in
 * place). checks/ is deliberately NOT extracted here — see checks.ts,
 * which stages private.tgz fresh into an ephemeral dir at check time and
 * deletes it after, so grader scripts are never resident between runs.
 * Called on every start AND every resume (unlike workspace files, which a
 * resume gets from restoreBackup instead).
 */
export async function hydratePressureScripts(rt: SessionRuntime, labSlug: string, labVersion: string): Promise<void> {
  const backend = rt.backend();
  const privateObj = await rt.env.LABS_BUCKET.get(privateKey(labSlug, labVersion));
  if (!privateObj) throw new Error(`private bundle missing for ${labSlug}@${labVersion}`);
  await backend.writeFile('/tmp/opalix-private.tgz', privateObj.body);
  await runOrThrow(
    rt,
    [
      'sh',
      '-c',
      "rm -rf /opt/lab && mkdir -m 700 -p /opt/lab && tar xzf /tmp/opalix-private.tgz -C /opt/lab --no-same-owner --wildcards 'pressure/*' 2>/dev/null; chown -R root:root /opt/lab && rm -f /tmp/opalix-private.tgz",
    ],
    'private bundle hydrate'
  );
}

/** Writes the session's env file the running services and any exec()'d command can source. */
export async function writeSessionEnv(rt: SessionRuntime, vars: Record<string, string>): Promise<void> {
  const lines = Object.entries(vars).map(([k, v]) => `${k}=${JSON.stringify(v)}`);
  const content = `# Generated by Opalix at session start. Do not edit.\n${lines.join('\n')}\n`;
  await rt.backend().writeFile('/etc/opalix/session.env', content);
}
