#!/usr/bin/env python3
"""The caller: stands in for a real agent that already depends on the
price-lookup virtual server. You do not edit this file -- a real caller
out in the world isn't yours to edit either, and it isn't yours to
re-deploy on your schedule.

What it assumes, and never re-checks: that the tool behind price-lookup
returns a bare number under structuredContent["result"] (the v1 contract).
What it does NOT assume: which exact tool name is currently live -- it
discovers that fresh from tools/list every run, the way a real MCP-based
agent would, rather than hard-coding a gateway-qualified tool name that
would only ever match one version.

Run it any time: `python3 caller.py`. It looks up three SKUs through the
stable price-lookup server, sums their prices, and reports whether the sum
matches what those three SKUs are actually known to cost. Prints exactly
one JSON line: {"pass": bool, "message": str}.
"""
import json
import os
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
STATE_PATH = os.path.join(HERE, "rollout", "state.yaml")

SKUS = ["sku-1", "sku-2", "sku-3"]
EXPECTED_TOTAL = 19.99 + 4.50 + 120.00  # what workspace/services/tool_server.py's PRICES actually says


def _load_state():
    with open(STATE_PATH) as f:
        text = f.read()
    # state.yaml is plain JSON with one leading '#' comment line -- see
    # contextforge/seed.py.
    lines = [ln for ln in text.splitlines() if not ln.lstrip().startswith("#")]
    return json.loads("\n".join(lines))


def _rpc(cf_url, server_id, token, method, params, id_):
    req = urllib.request.Request(
        "%s/servers/%s/mcp" % (cf_url, server_id),
        data=json.dumps({"jsonrpc": "2.0", "id": id_, "method": method, "params": params}).encode(),
        headers={
            "Authorization": "Bearer %s" % token,
            "Content-Type": "application/json",
            "Accept": "application/json, text/event-stream",
        },
    )
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.loads(resp.read())


def _finish(passed, message):
    print(json.dumps({"pass": bool(passed), "message": message}))
    sys.exit(0 if passed else 1)


def main():
    try:
        state = _load_state()
    except OSError:
        _finish(False, "rollout/state.yaml not found -- has contextforge/seed.py run yet?")
        return

    cf_url = state["contextforge_url"]
    server_id = state["server_id"]
    token = state["caller_token"]

    _rpc(cf_url, server_id, token, "initialize", {"protocolVersion": "2025-06-18", "capabilities": {}, "clientInfo": {"name": "caller", "version": "1"}}, 1)

    listing = _rpc(cf_url, server_id, token, "tools/list", {}, 2)
    tools = listing.get("result", {}).get("tools", [])
    if len(tools) != 1:
        _finish(False, "expected exactly one tool live on price-lookup, found %r" % ([t.get("name") for t in tools]))
        return
    tool_name = tools[0]["name"]

    total = 0.0
    for i, sku in enumerate(SKUS, start=3):
        resp = _rpc(cf_url, server_id, token, "tools/call", {"name": tool_name, "arguments": {"sku": sku}}, i)
        if "error" in resp:
            _finish(False, "tool call errored for %s: %r" % (sku, resp["error"]))
            return
        result = resp["result"]
        if result.get("isError"):
            _finish(False, "tool call reported isError for %s: %r" % (sku, result))
            return
        try:
            price = result["structuredContent"]["result"]  # the v1 contract this caller was built against
        except KeyError as e:
            _finish(False, "response for %s did not have the expected v1 shape (missing key %s): %r" % (sku, e, result))
            return
        total += price

    ok = abs(total - EXPECTED_TOTAL) < 1e-6
    _finish(ok, "total=%r expected=%r" % (total, EXPECTED_TOTAL))


if __name__ == "__main__":
    main()
